// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBULNUdDVZZT13Z5u0swqDv8y8QNfJjrjo',
    appId: '1:456330798296:web:0d49d7398ad49827cbe3ad',
    messagingSenderId: '456330798296',
    projectId: 'teacher-app-eebc9',
    authDomain: 'teacher-app-eebc9.firebaseapp.com',
    storageBucket: 'teacher-app-eebc9.appspot.com',
    measurementId: 'G-PYQ2CEG326',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHPZswZLZqZueyNJwBZlLD4g5SN2BhzVc',
    appId: '1:456330798296:android:8463948878e24485cbe3ad',
    messagingSenderId: '456330798296',
    projectId: 'teacher-app-eebc9',
    storageBucket: 'teacher-app-eebc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7viquTxYa61g5xgeDLm9SeUIRYUgVZ8',
    appId: '1:456330798296:ios:5226a28f06d2fc38cbe3ad',
    messagingSenderId: '456330798296',
    projectId: 'teacher-app-eebc9',
    storageBucket: 'teacher-app-eebc9.appspot.com',
    iosBundleId: 'com.release.teacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7viquTxYa61g5xgeDLm9SeUIRYUgVZ8',
    appId: '1:456330798296:ios:15b2cc876512b954cbe3ad',
    messagingSenderId: '456330798296',
    projectId: 'teacher-app-eebc9',
    storageBucket: 'teacher-app-eebc9.appspot.com',
    iosBundleId: 'com.example.teacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBULNUdDVZZT13Z5u0swqDv8y8QNfJjrjo',
    appId: '1:456330798296:web:6a670d4e51835ec8cbe3ad',
    messagingSenderId: '456330798296',
    projectId: 'teacher-app-eebc9',
    authDomain: 'teacher-app-eebc9.firebaseapp.com',
    storageBucket: 'teacher-app-eebc9.appspot.com',
    measurementId: 'G-S4D61CDXL1',
  );
}
